# Generated by Django 4.2.4 on 2023-08-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='base_date',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='base_time',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
